import type { Book } from '@/types/Book';

export const MOCK_FAVOURITES: Book[] = [
  {
    id: '1',
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    priceRegular: 600,
    priceDiscount: 450,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400',
    ],
    lang: 'uk',
    publicationYear: 2023,
    category: ['Classic'],
    description: ['A story of the fabulously wealthy Jay Gatsby...'],

    type: 'paperback',
    namespaceId: 'books',
    slug: 'the-great-gatsby',
    langAvailable: ['uk', 'en'],
    publication: 'Classic Press',
  },
  {
    id: '2',
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    priceRegular: 600,
    priceDiscount: 450,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400',
    ],
    lang: 'uk',
    publicationYear: 2023,
    category: ['Classic'],
    description: ['A story of the fabulously wealthy Jay Gatsby...'],

    type: 'paperback',
    namespaceId: 'books',
    slug: 'the-great-gatsby',
    langAvailable: ['uk', 'en'],
    publication: 'Classic Press',
  },
  {
    id: '3',
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    priceRegular: 600,
    priceDiscount: 450,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400',
    ],
    lang: 'uk',
    publicationYear: 2023,
    category: ['Classic'],
    description: ['A story of the fabulously wealthy Jay Gatsby...'],

    type: 'paperback',
    namespaceId: 'books',
    slug: 'the-great-gatsby',
    langAvailable: ['uk', 'en'],
    publication: 'Classic Press',
  },
  {
    id: '4',
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    priceRegular: 600,
    priceDiscount: 450,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400',
    ],
    lang: 'uk',
    publicationYear: 2023,
    category: ['Classic'],
    description: ['A story of the fabulously wealthy Jay Gatsby...'],

    type: 'paperback',
    namespaceId: 'books',
    slug: 'the-great-gatsby',
    langAvailable: ['uk', 'en'],
    publication: 'Classic Press',
  },
  {
    id: '5',
    name: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    priceRegular: 600,
    priceDiscount: 450,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400',
    ],
    lang: 'uk',
    publicationYear: 2023,
    category: ['Classic'],
    description: ['A story of the fabulously wealthy Jay Gatsby...'],

    type: 'paperback',
    namespaceId: 'books',
    slug: 'the-great-gatsby',
    langAvailable: ['uk', 'en'],
    publication: 'Classic Press',
  },
];
